<?php
declare(strict_types=1);

// OpenrouterModels SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

OpenrouterModelsUtility::setRegistrar(function (OpenrouterModelsUtility $u): void {
    $u->clean = [OpenrouterModelsClean::class, 'call'];
    $u->done = [OpenrouterModelsDone::class, 'call'];
    $u->make_error = [OpenrouterModelsMakeError::class, 'call'];
    $u->feature_add = [OpenrouterModelsFeatureAdd::class, 'call'];
    $u->feature_hook = [OpenrouterModelsFeatureHook::class, 'call'];
    $u->feature_init = [OpenrouterModelsFeatureInit::class, 'call'];
    $u->fetcher = [OpenrouterModelsFetcher::class, 'call'];
    $u->make_fetch_def = [OpenrouterModelsMakeFetchDef::class, 'call'];
    $u->make_context = [OpenrouterModelsMakeContext::class, 'call'];
    $u->make_options = [OpenrouterModelsMakeOptions::class, 'call'];
    $u->make_request = [OpenrouterModelsMakeRequest::class, 'call'];
    $u->make_response = [OpenrouterModelsMakeResponse::class, 'call'];
    $u->make_result = [OpenrouterModelsMakeResult::class, 'call'];
    $u->make_point = [OpenrouterModelsMakePoint::class, 'call'];
    $u->make_spec = [OpenrouterModelsMakeSpec::class, 'call'];
    $u->make_url = [OpenrouterModelsMakeUrl::class, 'call'];
    $u->param = [OpenrouterModelsParam::class, 'call'];
    $u->prepare_auth = [OpenrouterModelsPrepareAuth::class, 'call'];
    $u->prepare_body = [OpenrouterModelsPrepareBody::class, 'call'];
    $u->prepare_headers = [OpenrouterModelsPrepareHeaders::class, 'call'];
    $u->prepare_method = [OpenrouterModelsPrepareMethod::class, 'call'];
    $u->prepare_params = [OpenrouterModelsPrepareParams::class, 'call'];
    $u->prepare_path = [OpenrouterModelsPreparePath::class, 'call'];
    $u->prepare_query = [OpenrouterModelsPrepareQuery::class, 'call'];
    $u->graphql_body = [OpenrouterModelsGraphql::class, 'body'];
    $u->graphql_errors = [OpenrouterModelsGraphql::class, 'errors'];
    $u->result_basic = [OpenrouterModelsResultBasic::class, 'call'];
    $u->result_body = [OpenrouterModelsResultBody::class, 'call'];
    $u->result_headers = [OpenrouterModelsResultHeaders::class, 'call'];
    $u->transform_request = [OpenrouterModelsTransformRequest::class, 'call'];
    $u->transform_response = [OpenrouterModelsTransformResponse::class, 'call'];
});
