// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/openrouter-models-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.OpenrouterModelsSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.OpenrouterModelsSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.OpenrouterModelsSDK, name string) (sdk.OpenrouterModelsEntity, error) {
	switch strings.ToLower(name) {
	case "activity":
		return client.Activity(nil), nil
	case "api_key":
		return client.ApiKey(nil), nil
	case "app_ranking":
		return client.AppRanking(nil), nil
	case "beta_analytics":
		return client.BetaAnalytics(nil), nil
	case "bulk_add_workspace_member":
		return client.BulkAddWorkspaceMember(nil), nil
	case "bulk_assign_key":
		return client.BulkAssignKey(nil), nil
	case "bulk_assign_member":
		return client.BulkAssignMember(nil), nil
	case "bulk_remove_workspace_member":
		return client.BulkRemoveWorkspaceMember(nil), nil
	case "bulk_unassign_key":
		return client.BulkUnassignKey(nil), nil
	case "bulk_unassign_member":
		return client.BulkUnassignMember(nil), nil
	case "byok":
		return client.Byok(nil), nil
	case "chat_result":
		return client.ChatResult(nil), nil
	case "completion":
		return client.Completion(nil), nil
	case "create_observability_destination":
		return client.CreateObservabilityDestination(nil), nil
	case "credit":
		return client.Credit(nil), nil
	case "embedding":
		return client.Embedding(nil), nil
	case "endpoint":
		return client.Endpoint(nil), nil
	case "file":
		return client.File(nil), nil
	case "generation":
		return client.Generation(nil), nil
	case "generation_content_data":
		return client.GenerationContentData(nil), nil
	case "guardrail":
		return client.Guardrail(nil), nil
	case "image":
		return client.Image(nil), nil
	case "image_model_endpoint":
		return client.ImageModelEndpoint(nil), nil
	case "image_model_list_item":
		return client.ImageModelListItem(nil), nil
	case "key":
		return client.Key(nil), nil
	case "list_observability_destination":
		return client.ListObservabilityDestination(nil), nil
	case "list_preset_version":
		return client.ListPresetVersion(nil), nil
	case "member":
		return client.Member(nil), nil
	case "message":
		return client.Message(nil), nil
	case "model":
		return client.Model(nil), nil
	case "models_count":
		return client.ModelsCount(nil), nil
	case "models_list":
		return client.ModelsList(nil), nil
	case "o_auth":
		return client.OAuth(nil), nil
	case "observability_destination":
		return client.ObservabilityDestination(nil), nil
	case "open_responses_result":
		return client.OpenResponsesResult(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "preset":
		return client.Preset(nil), nil
	case "preset_version":
		return client.PresetVersion(nil), nil
	case "provider":
		return client.Provider(nil), nil
	case "rankings_daily":
		return client.RankingsDaily(nil), nil
	case "rerank":
		return client.Rerank(nil), nil
	case "response":
		return client.Response(nil), nil
	case "stt":
		return client.Stt(nil), nil
	case "submit_generation_feedback":
		return client.SubmitGenerationFeedback(nil), nil
	case "task":
		return client.Task(nil), nil
	case "tts":
		return client.Tts(nil), nil
	case "unified_benchmark":
		return client.UnifiedBenchmark(nil), nil
	case "update_byok_key":
		return client.UpdateByokKey(nil), nil
	case "update_guardrail":
		return client.UpdateGuardrail(nil), nil
	case "update_observability_destination":
		return client.UpdateObservabilityDestination(nil), nil
	case "update_workspace":
		return client.UpdateWorkspace(nil), nil
	case "upsert_workspace_budget":
		return client.UpsertWorkspaceBudget(nil), nil
	case "video":
		return client.Video(nil), nil
	case "video_generation":
		return client.VideoGeneration(nil), nil
	case "video_model":
		return client.VideoModel(nil), nil
	case "workspace":
		return client.Workspace(nil), nil
	case "workspace_budget":
		return client.WorkspaceBudget(nil), nil
	case "workspace_member":
		return client.WorkspaceMember(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
